
const blogs = [
    {
      id: "3958dc9e-712f-4277-85e9-fec4b6a64420",
      url: "is-it-smart-to-invest-in-cryptocurrency-in-2025",
      src: "/blog/blog-1.jpg",
      label: "Business",
      text: "Is it smart to invest in cryptocurrency in 2025? What you need to know",
      date: "Apr 27, 2024",
    },
    {
      id: "3958dc9e-712f-4377-85e9-fec4b6a64421",
      url: "how-to-save-money",
      src: "/blog/blog-2.jpg",
      label: "Finances",
      text: "How to save money - 8 simple ways to start saving money every month",
      date: "May 10, 2024",
      },
    {
      id: "3958dc9e-712f-4377-85e9-fec4b6a64422",
      url: "how-to-make-a-great-impression-from-the-first-moment",
      src: "/blog/blog-3.jpg",
      label: "Management",
      text: "21 job interview tips: How to make a great impression from the first moment",
      date: "Apr 1, 2024",
    },
    {
      id: "3958dc9e-712f-4377-85e9-fec4b6a64427",
      url: "what-is-an-etf-and-how-to-buy-them-from-your-banking-app",
      src: "/blog/blog-4.jpg",
      label: "Business",
      text: "Exchange Traded Fund (ETF): What is an ETF and how to buy them from your banking app",
      date: "Aug 16, 2024",
    },
    {
      id: "3958dc9e-712f-4377-85e9-fec4b6a64423",
      url: "the-smart-way-to-grow-your-money-while-you-sleep",
      src: "/blog/blog-5.jpg",
      label: "Management",
      text: "How to invest your money: The smart way to grow your money while you sleep",
      date: "May 10, 2024",
    },
    {
      id: "3958dc9e-712f-4377-85e9-fec4b6a64426",
      url: "how-to-maximize-your-productivity-while-working-from-home",
      src: "/blog/blog-6.jpg",
      label: "Finances",
      text: "A guide to working remotely: How to maximize productivity while working from home",
      date: "Jun 5, 2024",
    },
    {
      id: "3958dc9e-712f-4377-85e9-fec4b6a54427",
      url: "latest-technological-advancements-explored",
      src: "/blog/blog-1.jpg",
      label: "Business",
      text: "Latest technological advancements explored",
      date: "Aug 16, 2024",
    },
    {
      id: "3958dc9e-712f-4377-85e9-fec4b6a63423",
      url: "the-smart-way-to-grow-your-money-while-you-sleep",
      src: "/blog/blog-2.jpg",
      label: "Management",
      text: "How to invest your money: The smart way to grow your money while you sleep",
      date: "May 10, 2024",
    },
    {
      id: "6e82d1b3-6c6b-4b59-9bb0-afe0fe69a0b3",
      url: "reshaping-the-tech-industry-through-innovation",
      src: "/blog/blog-3.jpg",
      label: "Management",
      text: "Reshaping the tech industry through innovation",
      date: "Oct 12, 2024",
    },
    {
      id: "1c2d5f9e-8f8d-4e91-b0af-31b2e2a54f71",
      url: "latest-industry-trends-analyzed",
      src: "/blog/blog-4.jpg",
      label: "Finances",
      text: "Latest industry trends analyzed",
      date: "Nov 21, 2024",
    },
  ];
  
  module.exports = {
    blogs,
  };