import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.className} antialiased bg-background-100`}>
      <Header />
      <main className="relative flex flex-col">
        <div className="flex-grow flex-1">
          {children}       
        </div>
      </main>
      {/* <Footer /> */}
    </body>
  </html>
  );
}
